"""Initial V62 Schema - Complete Enterprise Master

Revision ID: 9723fce6ec55
Revises: 
Create Date: 2025-12-27 04:37:19.273477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9723fce6ec55'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('version_number', sa.String(length=20), nullable=False),
    sa.Column('build_number', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.Column('download_url', sa.String(length=500), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_versions_id'), 'app_versions', ['id'], unique=False)
    op.create_table('data_retention_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.Enum('DELETE', 'ARCHIVE_TO_COLD_STORAGE', name='retentionstrategy'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_name')
    )
    op.create_index(op.f('ix_data_retention_policies_id'), 'data_retention_policies', ['id'], unique=False)
    op.create_table('identity_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret', sa.String(length=500), nullable=False),
    sa.Column('issuer_url', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_providers_id'), 'identity_providers', ['id'], unique=False)
    op.create_table('plan_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_type', sa.Enum('DIGITAL', 'EXPERT', 'MONITOR_360', name='plantype'), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('limit_value', sa.Integer(), nullable=False),
    sa.Column('overage_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Defines resource limits for each subscription plan'
    )
    op.create_index(op.f('ix_plan_limits_id'), 'plan_limits', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('HARDWARE_KIT', 'SENSOR_UNIT', 'SETUP_FEE', 'CONSULTING_HOUR', 'SPARE_PART', name='productcategory'), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('OWNER', 'STAFF', 'ADMIN', 'TECHNICIAN', 'GUARD', 'INCIDENT_COMMANDER', 'WAREHOUSE_MANAGER', 'PROCUREMENT_MANAGER', 'SUSTAINABILITY_MANAGER', 'SAFETY_OFFICER', 'BIM_MANAGER', 'FINANCIAL_AUDITOR', 'TRAINING_MANAGER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('sso_provider_id', sa.Integer(), nullable=True),
    sa.Column('federated_id', sa.String(length=255), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('fcm_token', sa.String(length=500), nullable=True),
    sa.Column('technician_skills', sa.JSON(), nullable=True),
    sa.Column('bank_details', sa.JSON(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('company_logo_url', sa.String(length=500), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sso_provider_id'], ['identity_providers.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('vendor_type', sa.String(length=50), nullable=True),
    sa.Column('bank_details', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tax_id')
    )
    op.create_index(op.f('ix_vendors_id'), 'vendors', ['id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key_name', sa.String(length=100), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_api_key'), 'api_keys', ['api_key'], unique=True)
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('billing_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('batch_name', sa.String(length=255), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=True),
    sa.Column('invoice_pdf_url', sa.String(length=500), nullable=True),
    sa.Column('sii_folio', sa.String(length=100), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_batches_id'), 'billing_batches', ['id'], unique=False)
    op.create_table('budget_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('budget_limit_amount', sa.Float(), nullable=False),
    sa.Column('current_spend_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_centers_code'), 'budget_centers', ['code'], unique=False)
    op.create_index(op.f('ix_budget_centers_id'), 'budget_centers', ['id'], unique=False)
    op.create_table('client_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('contract_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('monthly_value', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('adjustment_index', sa.Enum('CPI', 'UF', 'FIXED_PERCENTAGE', 'NONE', name='adjustmentindex'), nullable=True),
    sa.Column('next_adjustment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'EXPIRED', 'TERMINATED', 'RENEWED', name='contractstatus'), nullable=True),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_contracts_contract_number'), 'client_contracts', ['contract_number'], unique=True)
    op.create_index(op.f('ix_client_contracts_id'), 'client_contracts', ['id'], unique=False)
    op.create_table('dashboard_layouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_layouts_id'), 'dashboard_layouts', ['id'], unique=False)
    op.create_table('emission_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('resource_name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('co2_factor', sa.Float(), nullable=False),
    sa.Column('emission_scope', sa.Enum('SCOPE_1', 'SCOPE_2', 'SCOPE_3', name='emissionscope'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emission_factors_id'), 'emission_factors', ['id'], unique=False)
    op.create_table('failure_hierarchies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failure_hierarchies_id'), 'failure_hierarchies', ['id'], unique=False)
    op.create_table('generated_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.Enum('MAINTENANCE_MONTHLY', 'FINANCIAL_SUMMARY', 'INCIDENT_REPORT', 'SLA_COMPLIANCE', 'ASSET_HEALTH', name='reporttype'), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_snapshot', sa.JSON(), nullable=False),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_reports_id'), 'generated_reports', ['id'], unique=False)
    op.create_table('i18n_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('translated_value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_i18n_content_id'), 'i18n_content', ['id'], unique=False)
    op.create_table('locales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('floor_plan_url', sa.String(length=500), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('cost_center_code', sa.String(length=50), nullable=True),
    sa.Column('tax_rate_override', sa.Float(), nullable=True),
    sa.Column('geofence_polygon', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locales_id'), 'locales', ['id'], unique=False)
    op.create_table('notification_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('subject_template', sa.String(length=500), nullable=True),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_templates_id'), 'notification_templates', ['id'], unique=False)
    op.create_table('otp_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_codes_id'), 'otp_codes', ['id'], unique=False)
    op.create_table('product_vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('vendor_sku', sa.String(length=100), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('is_preferred', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_vendors_id'), 'product_vendors', ['id'], unique=False)
    op.create_table('purchase_requisitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'ORDERED', name='requisitionstatus'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_requisitions_id'), 'purchase_requisitions', ['id'], unique=False)
    op.create_table('risk_matrices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('severity_levels', sa.JSON(), nullable=False),
    sa.Column('probability_levels', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_matrices_id'), 'risk_matrices', ['id'], unique=False)
    op.create_table('sustainability_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('target_reduction_percentage', sa.Float(), nullable=False),
    sa.Column('baseline_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sustainability_goals_id'), 'sustainability_goals', ['id'], unique=False)
    op.create_table('technician_certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technician_certifications_id'), 'technician_certifications', ['id'], unique=False)
    op.create_table('technician_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('shift_type', sa.Enum('WORKING', 'DAY_OFF', 'SICK_LEAVE', 'VACATION', name='shifttype'), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technician_shifts_id'), 'technician_shifts', ['id'], unique=False)
    op.create_table('training_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_url', sa.String(length=500), nullable=True),
    sa.Column('min_score_to_pass', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('required_for_asset_category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_modules_id'), 'training_modules', ['id'], unique=False)
    op.create_table('usage_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('billing_period', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_id'), 'usage_records', ['id'], unique=False)
    op.create_index(op.f('ix_usage_records_timestamp'), 'usage_records', ['timestamp'], unique=False)
    op.create_table('user_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_uuid', sa.String(length=255), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('os_version', sa.String(length=50), nullable=True),
    sa.Column('app_version', sa.String(length=50), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_devices_device_uuid'), 'user_devices', ['device_uuid'], unique=True)
    op.create_index(op.f('ix_user_devices_id'), 'user_devices', ['id'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('warehouse_type', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('responsible_user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    op.create_table('bim_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model_file_url', sa.String(length=500), nullable=False),
    sa.Column('viewer_urn', sa.String(length=500), nullable=True),
    sa.Column('format', sa.Enum('IFC', 'RVT', 'NWD', 'OBJ', name='bimformat'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['local_id'], ['locales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bim_models_id'), 'bim_models', ['id'], unique=False)
    op.create_table('dashboard_widgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layout_id', sa.Integer(), nullable=False),
    sa.Column('widget_type', sa.Enum('CHART_LINE', 'CHART_BAR', 'CHART_PIE', 'KPI_CARD', 'LIST_RECENT', 'MAP_VIEW', name='widgettype'), nullable=False),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.Column('position_x', sa.Integer(), nullable=False),
    sa.Column('position_y', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['layout_id'], ['dashboard_layouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_widgets_id'), 'dashboard_widgets', ['id'], unique=False)
    op.create_table('failure_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hierarchy_id', sa.Integer(), nullable=False),
    sa.Column('parent_code_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('code_type', sa.Enum('PROBLEM', 'CAUSE', 'REMEDY', name='failurecodetype'), nullable=False),
    sa.ForeignKeyConstraint(['hierarchy_id'], ['failure_hierarchies.id'], ),
    sa.ForeignKeyConstraint(['parent_code_id'], ['failure_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failure_codes_id'), 'failure_codes', ['id'], unique=False)
    op.create_table('inventory_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('min_stock', sa.Float(), nullable=True),
    sa.Column('max_stock', sa.Float(), nullable=True),
    sa.Column('reorder_point', sa.Float(), nullable=True),
    sa.Column('auto_replenish', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_stocks_id'), 'inventory_stocks', ['id'], unique=False)
    op.create_table('local_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('floor_plan_url', sa.String(length=500), nullable=True),
    sa.Column('is_bookable', sa.Boolean(), nullable=True),
    sa.Column('capacity_people', sa.Integer(), nullable=True),
    sa.Column('criticality', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['local_id'], ['locales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_local_areas_id'), 'local_areas', ['id'], unique=False)
    op.create_table('local_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'STAFF', 'ADMIN', 'TECHNICIAN', 'GUARD', 'INCIDENT_COMMANDER', 'WAREHOUSE_MANAGER', 'PROCUREMENT_MANAGER', 'SUSTAINABILITY_MANAGER', 'SAFETY_OFFICER', 'BIM_MANAGER', 'FINANCIAL_AUDITOR', 'TRAINING_MANAGER', name='userrole'), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['local_id'], ['locales.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_local_members_id'), 'local_members', ['id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=True),
    sa.Column('po_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'PARTIALLY_RECEIVED', 'FULLY_RECEIVED', 'CANCELLED', 'CLOSED', name='postatus'), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requisition_id'], ['purchase_requisitions.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_id'), 'purchase_orders', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_table('quality_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('auditor_id', sa.Integer(), nullable=False),
    sa.Column('form_template_id', sa.Integer(), nullable=True),
    sa.Column('score_obtained', sa.Float(), nullable=False),
    sa.Column('score_max', sa.Float(), nullable=False),
    sa.Column('compliance_percentage', sa.Float(), nullable=False),
    sa.Column('audit_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['auditor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['local_id'], ['locales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_audits_id'), 'quality_audits', ['id'], unique=False)
    op.create_table('requisition_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_requested', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['requisition_id'], ['purchase_requisitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requisition_items_id'), 'requisition_items', ['id'], unique=False)
    op.create_table('shift_handovers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('outgoing_user_id', sa.Integer(), nullable=False),
    sa.Column('incoming_user_id', sa.Integer(), nullable=False),
    sa.Column('handover_notes', sa.Text(), nullable=False),
    sa.Column('critical_alerts_pending', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['incoming_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['local_id'], ['locales.id'], ),
    sa.ForeignKeyConstraint(['outgoing_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_handovers_id'), 'shift_handovers', ['id'], unique=False)
    op.create_table('sync_cursors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('last_row_version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['user_devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_cursors_id'), 'sync_cursors', ['id'], unique=False)
    op.create_table('training_quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('questions_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['training_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_quizzes_id'), 'training_quizzes', ['id'], unique=False)
    op.create_table('user_training_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ASSIGNED', 'IN_PROGRESS', 'PASSED', 'FAILED', name='trainingstatus'), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('certificate_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['training_modules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_training_progress_id'), 'user_training_progress', ['id'], unique=False)
    op.create_table('visitor_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=False),
    sa.Column('visitor_name', sa.String(length=255), nullable=False),
    sa.Column('visitor_rut', sa.String(length=50), nullable=True),
    sa.Column('visitor_email', sa.String(length=255), nullable=True),
    sa.Column('qr_token', sa.String(length=255), nullable=False),
    sa.Column('expected_arrival', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('INVITED', 'PRE_REGISTERED', 'CHECKED_IN', 'CHECKED_OUT', 'BLACKLISTED', name='visitorstatus'), nullable=True),
    sa.Column('nda_signed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['local_id'], ['locales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitor_invites_id'), 'visitor_invites', ['id'], unique=False)
    op.create_index(op.f('ix_visitor_invites_qr_token'), 'visitor_invites', ['qr_token'], unique=True)
    op.create_table('workflow_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.Enum('OPEN', 'QUOTING', 'PENDING_PAYMENT', 'PAID', 'ASSIGNED', 'OFFERED', 'IN_PROGRESS', 'ON_HOLD', 'REVIEW', 'COMPLETED', 'CANCELLED', 'BILLED_IN_BATCH', name='ticketstatus'), nullable=False),
    sa.Column('to_status', sa.Enum('OPEN', 'QUOTING', 'PENDING_PAYMENT', 'PAID', 'ASSIGNED', 'OFFERED', 'IN_PROGRESS', 'ON_HOLD', 'REVIEW', 'COMPLETED', 'CANCELLED', 'BILLED_IN_BATCH', name='ticketstatus'), nullable=False),
    sa.Column('required_role', sa.Enum('OWNER', 'STAFF', 'ADMIN', 'TECHNICIAN', 'GUARD', 'INCIDENT_COMMANDER', 'WAREHOUSE_MANAGER', 'PROCUREMENT_MANAGER', 'SUSTAINABILITY_MANAGER', 'SAFETY_OFFICER', 'BIM_MANAGER', 'FINANCIAL_AUDITOR', 'TRAINING_MANAGER', name='userrole'), nullable=True),
    sa.Column('required_form_template_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_steps_id'), 'workflow_steps', ['id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('parent_asset_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('qr_code', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('category', sa.Enum('HARDWARE_KIT', 'SENSOR_UNIT', 'SETUP_FEE', 'CONSULTING_HOUR', 'SPARE_PART', name='productcategory'), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('OPERATIONAL', 'MAINTENANCE', 'DOWN', 'IN_STORAGE', 'DISPOSED', name='assetstatus'), nullable=True),
    sa.Column('manual_pdf_url', sa.String(length=500), nullable=True),
    sa.Column('warranty_pdf_url', sa.String(length=500), nullable=True),
    sa.Column('installation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('warranty_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_maintenance_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_meter_reading', sa.Float(), nullable=True),
    sa.Column('meter_unit', sa.String(length=50), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('residual_value', sa.Float(), nullable=True),
    sa.Column('map_position_x', sa.Float(), nullable=True),
    sa.Column('map_position_y', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['local_areas.id'], ),
    sa.ForeignKeyConstraint(['local_id'], ['locales.id'], ),
    sa.ForeignKeyConstraint(['parent_asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_qr_code'), 'assets', ['qr_code'], unique=True)
    op.create_table('goods_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('received_by', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('delivery_note_number', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_receipts_id'), 'goods_receipts', ['id'], unique=False)
    op.create_table('po_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_ordered', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('quantity_received', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_po_items_id'), 'po_items', ['id'], unique=False)
    op.create_table('visitor_ndas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visitor_invite_id', sa.Integer(), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['visitor_invite_id'], ['visitor_invites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitor_ndas_id'), 'visitor_ndas', ['id'], unique=False)
    op.create_table('asset_bom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_required', sa.Integer(), nullable=False),
    sa.Column('criticality', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_bom_id'), 'asset_bom', ['id'], unique=False)
    op.create_table('asset_depreciation_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('STRAIGHT_LINE', 'DOUBLE_DECLINING', name='depreciationmethod'), nullable=False),
    sa.Column('useful_life_years', sa.Integer(), nullable=False),
    sa.Column('current_book_value', sa.Float(), nullable=False),
    sa.Column('last_calculated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_depreciation_schedules_id'), 'asset_depreciation_schedules', ['id'], unique=False)
    op.create_table('asset_health_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('predicted_failure_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prediction_confidence', sa.Float(), nullable=True),
    sa.Column('contributing_factors', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_health_history_id'), 'asset_health_history', ['id'], unique=False)
    op.create_index(op.f('ix_asset_health_history_timestamp'), 'asset_health_history', ['timestamp'], unique=False)
    op.create_table('asset_maintenance_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('frequency_days', sa.Integer(), nullable=True),
    sa.Column('next_due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('frequency_meter', sa.Float(), nullable=True),
    sa.Column('next_due_meter', sa.Float(), nullable=True),
    sa.Column('protocol_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_maintenance_plans_id'), 'asset_maintenance_plans', ['id'], unique=False)
    op.create_table('bim_object_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bim_model_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('object_guid', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['bim_model_id'], ['bim_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bim_object_mappings_id'), 'bim_object_mappings', ['id'], unique=False)
    op.create_table('iot_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.String(length=100), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iot_devices_id'), 'iot_devices', ['id'], unique=False)
    op.create_table('loto_procedures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('procedure_steps', sa.Text(), nullable=False),
    sa.Column('required_locks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loto_procedures_id'), 'loto_procedures', ['id'], unique=False)
    op.create_table('service_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('assigned_technician_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('ticket_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'QUOTING', 'PENDING_PAYMENT', 'PAID', 'ASSIGNED', 'OFFERED', 'IN_PROGRESS', 'ON_HOLD', 'REVIEW', 'COMPLETED', 'CANCELLED', 'BILLED_IN_BATCH', name='ticketstatus'), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticketpriority'), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sla_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_diagnosis', sa.Text(), nullable=True),
    sa.Column('visit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('work_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('work_ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('technician_notes', sa.Text(), nullable=True),
    sa.Column('customer_signature_url', sa.String(length=500), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quoted_price', sa.Float(), nullable=True),
    sa.Column('provider_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['assigned_technician_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['local_id'], ['locales.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_tickets_id'), 'service_tickets', ['id'], unique=False)
    op.create_table('access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('guard_user_id', sa.Integer(), nullable=False),
    sa.Column('visitor_invite_id', sa.Integer(), nullable=True),
    sa.Column('visitor_name', sa.String(length=255), nullable=False),
    sa.Column('visitor_rut', sa.String(length=50), nullable=True),
    sa.Column('access_type', sa.Enum('VISITOR', 'CONTRACTOR', 'DELIVERY', 'EMPLOYEE', name='accesstype'), nullable=False),
    sa.Column('related_ticket_id', sa.Integer(), nullable=True),
    sa.Column('check_in_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('check_out_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vehicle_plate', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['guard_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['local_id'], ['locales.id'], ),
    sa.ForeignKeyConstraint(['related_ticket_id'], ['service_tickets.id'], ),
    sa.ForeignKeyConstraint(['visitor_invite_id'], ['visitor_invites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_logs_id'), 'access_logs', ['id'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('from_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('to_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('movement_type', sa.Enum('PURCHASE', 'TRANSFER', 'CONSUMPTION', 'ADJUSTMENT', 'RETURN', name='movementtype'), nullable=False),
    sa.Column('reference_ticket_id', sa.Integer(), nullable=True),
    sa.Column('performed_by', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['reference_ticket_id'], ['service_tickets.id'], ),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movements_id'), 'inventory_movements', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_timestamp'), 'inventory_movements', ['timestamp'], unique=False)
    op.create_table('loto_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('ACTIVE', 'REMOVED', name='lotostatus'), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['service_tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loto_logs_id'), 'loto_logs', ['id'], unique=False)
    op.create_table('ticket_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['service_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_attachments_id'), 'ticket_attachments', ['id'], unique=False)
    op.create_table('ticket_failure_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('problem_code_id', sa.Integer(), nullable=False),
    sa.Column('cause_code_id', sa.Integer(), nullable=False),
    sa.Column('remedy_code_id', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cause_code_id'], ['failure_codes.id'], ),
    sa.ForeignKeyConstraint(['problem_code_id'], ['failure_codes.id'], ),
    sa.ForeignKeyConstraint(['remedy_code_id'], ['failure_codes.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['service_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_failure_reports_id'), 'ticket_failure_reports', ['id'], unique=False)
    op.create_table('ticket_penalties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('sla_rule_id', sa.Integer(), nullable=True),
    sa.Column('delay_minutes', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('is_contested', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['service_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_penalties_id'), 'ticket_penalties', ['id'], unique=False)
    op.create_table('ticket_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.Column('required_photo', sa.Boolean(), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['service_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_tasks_id'), 'ticket_tasks', ['id'], unique=False)
    op.create_table('work_permits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('risk_matrix_id', sa.Integer(), nullable=True),
    sa.Column('risk_assessment', sa.Text(), nullable=False),
    sa.Column('calculated_risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'EXTREME', name='risklevel'), nullable=False),
    sa.Column('supervisor_signature_url', sa.String(length=500), nullable=True),
    sa.Column('technician_signature_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['risk_matrix_id'], ['risk_matrices.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['service_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_permits_id'), 'work_permits', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_permits_id'), table_name='work_permits')
    op.drop_table('work_permits')
    op.drop_index(op.f('ix_ticket_tasks_id'), table_name='ticket_tasks')
    op.drop_table('ticket_tasks')
    op.drop_index(op.f('ix_ticket_penalties_id'), table_name='ticket_penalties')
    op.drop_table('ticket_penalties')
    op.drop_index(op.f('ix_ticket_failure_reports_id'), table_name='ticket_failure_reports')
    op.drop_table('ticket_failure_reports')
    op.drop_index(op.f('ix_ticket_attachments_id'), table_name='ticket_attachments')
    op.drop_table('ticket_attachments')
    op.drop_index(op.f('ix_loto_logs_id'), table_name='loto_logs')
    op.drop_table('loto_logs')
    op.drop_index(op.f('ix_inventory_movements_timestamp'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_id'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_access_logs_id'), table_name='access_logs')
    op.drop_table('access_logs')
    op.drop_index(op.f('ix_service_tickets_id'), table_name='service_tickets')
    op.drop_table('service_tickets')
    op.drop_index(op.f('ix_loto_procedures_id'), table_name='loto_procedures')
    op.drop_table('loto_procedures')
    op.drop_index(op.f('ix_iot_devices_id'), table_name='iot_devices')
    op.drop_table('iot_devices')
    op.drop_index(op.f('ix_bim_object_mappings_id'), table_name='bim_object_mappings')
    op.drop_table('bim_object_mappings')
    op.drop_index(op.f('ix_asset_maintenance_plans_id'), table_name='asset_maintenance_plans')
    op.drop_table('asset_maintenance_plans')
    op.drop_index(op.f('ix_asset_health_history_timestamp'), table_name='asset_health_history')
    op.drop_index(op.f('ix_asset_health_history_id'), table_name='asset_health_history')
    op.drop_table('asset_health_history')
    op.drop_index(op.f('ix_asset_depreciation_schedules_id'), table_name='asset_depreciation_schedules')
    op.drop_table('asset_depreciation_schedules')
    op.drop_index(op.f('ix_asset_bom_id'), table_name='asset_bom')
    op.drop_table('asset_bom')
    op.drop_index(op.f('ix_visitor_ndas_id'), table_name='visitor_ndas')
    op.drop_table('visitor_ndas')
    op.drop_index(op.f('ix_po_items_id'), table_name='po_items')
    op.drop_table('po_items')
    op.drop_index(op.f('ix_goods_receipts_id'), table_name='goods_receipts')
    op.drop_table('goods_receipts')
    op.drop_index(op.f('ix_assets_qr_code'), table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_workflow_steps_id'), table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_index(op.f('ix_visitor_invites_qr_token'), table_name='visitor_invites')
    op.drop_index(op.f('ix_visitor_invites_id'), table_name='visitor_invites')
    op.drop_table('visitor_invites')
    op.drop_index(op.f('ix_user_training_progress_id'), table_name='user_training_progress')
    op.drop_table('user_training_progress')
    op.drop_index(op.f('ix_training_quizzes_id'), table_name='training_quizzes')
    op.drop_table('training_quizzes')
    op.drop_index(op.f('ix_sync_cursors_id'), table_name='sync_cursors')
    op.drop_table('sync_cursors')
    op.drop_index(op.f('ix_shift_handovers_id'), table_name='shift_handovers')
    op.drop_table('shift_handovers')
    op.drop_index(op.f('ix_requisition_items_id'), table_name='requisition_items')
    op.drop_table('requisition_items')
    op.drop_index(op.f('ix_quality_audits_id'), table_name='quality_audits')
    op.drop_table('quality_audits')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_local_members_id'), table_name='local_members')
    op.drop_table('local_members')
    op.drop_index(op.f('ix_local_areas_id'), table_name='local_areas')
    op.drop_table('local_areas')
    op.drop_index(op.f('ix_inventory_stocks_id'), table_name='inventory_stocks')
    op.drop_table('inventory_stocks')
    op.drop_index(op.f('ix_failure_codes_id'), table_name='failure_codes')
    op.drop_table('failure_codes')
    op.drop_index(op.f('ix_dashboard_widgets_id'), table_name='dashboard_widgets')
    op.drop_table('dashboard_widgets')
    op.drop_index(op.f('ix_bim_models_id'), table_name='bim_models')
    op.drop_table('bim_models')
    op.drop_index(op.f('ix_workflows_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_user_devices_id'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_device_uuid'), table_name='user_devices')
    op.drop_table('user_devices')
    op.drop_index(op.f('ix_usage_records_timestamp'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_id'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_training_modules_id'), table_name='training_modules')
    op.drop_table('training_modules')
    op.drop_index(op.f('ix_technician_shifts_id'), table_name='technician_shifts')
    op.drop_table('technician_shifts')
    op.drop_index(op.f('ix_technician_certifications_id'), table_name='technician_certifications')
    op.drop_table('technician_certifications')
    op.drop_index(op.f('ix_sustainability_goals_id'), table_name='sustainability_goals')
    op.drop_table('sustainability_goals')
    op.drop_index(op.f('ix_risk_matrices_id'), table_name='risk_matrices')
    op.drop_table('risk_matrices')
    op.drop_index(op.f('ix_purchase_requisitions_id'), table_name='purchase_requisitions')
    op.drop_table('purchase_requisitions')
    op.drop_index(op.f('ix_product_vendors_id'), table_name='product_vendors')
    op.drop_table('product_vendors')
    op.drop_index(op.f('ix_otp_codes_id'), table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_index(op.f('ix_notification_templates_id'), table_name='notification_templates')
    op.drop_table('notification_templates')
    op.drop_index(op.f('ix_locales_id'), table_name='locales')
    op.drop_table('locales')
    op.drop_index(op.f('ix_i18n_content_id'), table_name='i18n_content')
    op.drop_table('i18n_content')
    op.drop_index(op.f('ix_generated_reports_id'), table_name='generated_reports')
    op.drop_table('generated_reports')
    op.drop_index(op.f('ix_failure_hierarchies_id'), table_name='failure_hierarchies')
    op.drop_table('failure_hierarchies')
    op.drop_index(op.f('ix_emission_factors_id'), table_name='emission_factors')
    op.drop_table('emission_factors')
    op.drop_index(op.f('ix_dashboard_layouts_id'), table_name='dashboard_layouts')
    op.drop_table('dashboard_layouts')
    op.drop_index(op.f('ix_client_contracts_id'), table_name='client_contracts')
    op.drop_index(op.f('ix_client_contracts_contract_number'), table_name='client_contracts')
    op.drop_table('client_contracts')
    op.drop_index(op.f('ix_budget_centers_id'), table_name='budget_centers')
    op.drop_index(op.f('ix_budget_centers_code'), table_name='budget_centers')
    op.drop_table('budget_centers')
    op.drop_index(op.f('ix_billing_batches_id'), table_name='billing_batches')
    op.drop_table('billing_batches')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_api_key'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_vendors_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_plan_limits_id'), table_name='plan_limits')
    op.drop_table('plan_limits')
    op.drop_index(op.f('ix_identity_providers_id'), table_name='identity_providers')
    op.drop_table('identity_providers')
    op.drop_index(op.f('ix_data_retention_policies_id'), table_name='data_retention_policies')
    op.drop_table('data_retention_policies')
    op.drop_index(op.f('ix_app_versions_id'), table_name='app_versions')
    op.drop_table('app_versions')
    # ### end Alembic commands ###
